name: Render PlantUML

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WIKI_TOKEN }}
      - name: Render PlantUML to wiki
        uses: frederikheld/render-plantuml-to-wiki-action@v1.0.2
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
          INPUT_DIR: 'pant'
          OUTPUT_DIR: 'pant/out'
